import json
import logging
import asyncio
import os
from typing import Any

from openai import (
    AsyncOpenAI,
    APITimeoutError,
    APIConnectionError,
    APIStatusError,
    BadRequestError,
    RateLimitError,
)

from app.cache import get_cached, make_cache_key, set_cached
from app.config import openai_model, openai_temperature
from app.models import FeedbackRequest, FeedbackResponse

"""Feedback logic handling system prompt, LLM interaction, and response parsing
- Handles all communication with OpenAI API
- Uses Structured Outputs (response_format with json_schema and strict=True) to guarantee
every response matches the schema exactly, removing the need for manual
JSON parsing or retry loops for malformed output.

System prompt designed with the following goals in mind:
1. LLM has clear instructions and few-shot examples for reference
2. And OpenAI auto prompt caching is used
- Since system prompt is identical across all requests, it gets cached after first call, 
and cuts input costs and latency

Additional features:
- Retry logic with exponential backoff
- Post-processing validation to enforce logical consistency (for example, is_correct
  must match whether errors list is empty)
"""

logger = logging.getLogger(__name__)

# Singleton client to reuse underlying HTTP connection pool to prevent time wastage on TLS handshakes
_client: AsyncOpenAI | None = None


def _get_client() -> AsyncOpenAI:
    """Returns shared OpenAI client, creating it on first use"""
    global _client
    if _client is None:
        _client = AsyncOpenAI(timeout=25.0)
    return _client


# System prompt design choices:
# - Few-shot examples cover different writing systems (Latin, CJK, Cyrillic,
#   Arabic) and error types (conjugation, gender, particles, spelling, case,
#   missing words) so the model sees the expected output shape for each pattern
# - Examples 1-4 and 7 are from the task-provided sample_inputs.json
# - Examples 5, 6, 8-10 were generated by the model then verified for
#   linguistic accuracy via web research (sources documented in integration
#   tests), they exist to demonstrate output format for non-Latin scripts,
#   and not to teach the model grammar it already knows
# - Explicit constraints: every allowed error_type and difficulty level is
#   listed so the model never invents invalid values
# - The prompt is kept static so OpenAI can auto-cache it after the first call,
#   cutting input token costs

SYSTEM_PROMPT = """\
You are an expert language tutor who helps students learn foreign languages. \
A student will give you a sentence they wrote in their target language. Your \
job is to carefully analyze the sentence for errors and return structured \
feedback as JSON.

STEP-BY-STEP PROCESS:
1. Read the sentence carefully word by word.
2. Identify every grammatical, spelling, or usage error.
3. For each error, determine the minimal span of text that is wrong.
4. Classify each error using exactly one of the allowed error types.
5. Write a short, friendly explanation in the student's NATIVE language (not the target language -- this is essential for learner comprehension).
6. Build the corrected sentence by applying all fixes at once.
7. Decide if the original sentence was correct (no errors at all).
8. Rate the CEFR difficulty based on what the student attempted.

CRITICAL RULES:
- If the sentence is already correct, you MUST set is_correct to true, \
return an empty errors array, and set corrected_sentence to the original \
sentence exactly as written. Do not change spacing, punctuation, or \
capitalization of a correct sentence.
- If there are errors, you MUST set is_correct to false and list every error. \
Never return is_correct=true when there are errors.
- Never return is_correct=false with an empty errors array.
- The corrected_sentence must be the minimal fix that preserves the student's \
original meaning, voice, and style. Do not rephrase, restructure, or \
"improve" the sentence beyond fixing actual errors.
- Do not add errors that are not there. Be conservative: if a phrasing is \
unusual but grammatically acceptable, do not flag it.

ALLOWED ERROR TYPES (use exactly these lowercase strings):
- grammar: general grammar mistakes not covered by a more specific type below
- spelling: a word is misspelled
- word_choice: the wrong word is used where a different word is needed
- punctuation: missing, extra, or incorrect punctuation marks
- word_order: words are in the wrong order for the language's grammar
- missing_word: a required word is absent from the sentence
- extra_word: an unnecessary word is present in the sentence
- conjugation: a verb is conjugated incorrectly (wrong tense, person, or mood)
- gender_agreement: a noun, adjective, article, or pronoun has the wrong gender
- number_agreement: singular/plural mismatch between words that must agree
- tone_register: the formality level is inappropriate for the context
- other: anything that does not fit the categories above

CEFR DIFFICULTY LEVELS (rate based on what the student ATTEMPTED, not errors):
- A1: very basic phrases -- greetings, introductions, simple present tense, \
basic vocabulary (colors, numbers, family members)
- A2: simple everyday topics -- shopping, directions, past tense, common \
connectors (and, but, because)
- B1: familiar topics with some complexity -- opinions, experiences, future \
plans, relative clauses, a range of tenses
- B2: complex and abstract topics -- arguments, hypotheticals, conditional \
sentences, formal writing, passive voice
- C1: advanced structures -- subjunctive mood, nuanced idioms, academic \
vocabulary, complex subordinate clauses
- C2: near-native complexity -- literary style, rare grammatical forms, \
subtle register shifts, sophisticated rhetoric

RULES FOR THE "original" FIELD:
- The original field MUST be an exact substring of the student's input sentence.
- For missing_word errors, use the words immediately around the gap.
- Keep the original span as short as possible while clearly identifying the error.
- Never paraphrase or modify the original text.

RULES FOR EXPLANATIONS:
- IMPORTANT: Write every explanation in the student's NATIVE language, not the target language. If the native language is English, write in English. If the native language is Spanish, write in Spanish. NEVER write explanations in the target language. This is critical because a beginner cannot read explanations in the language they are still learning.
- Keep explanations to 1-2 sentences maximum.
- Be encouraging and educational, not critical or condescending.
- Explain WHY the correction is needed, not just what changed.
- Use simple terms a beginner would understand.

EXAMPLES:

Example 1 -- Spanish conjugation error:
Input: Target=Spanish, Native=English, Sentence="Yo soy fue al mercado ayer."
Output:
{
  "corrected_sentence": "Yo fui al mercado ayer.",
  "is_correct": false,
  "errors": [
    {
      "original": "soy fue",
      "correction": "fui",
      "error_type": "conjugation",
      "explanation": "You mixed two verb forms here. 'Soy' is the present tense of 'ser' (to be), and 'fue' is a past tense form of 'ir' (to go). Since you want to say 'I went' in the past, you just need 'fui'."
    }
  ],
  "difficulty": "A2"
}

Example 2 -- French gender agreement (multiple errors):
Input: Target=French, Native=English, Sentence="La chat noir est sur le table."
Output:
{
  "corrected_sentence": "Le chat noir est sur la table.",
  "is_correct": false,
  "errors": [
    {
      "original": "La chat",
      "correction": "Le chat",
      "error_type": "gender_agreement",
      "explanation": "'Chat' (cat) is a masculine noun in French, so it needs the masculine article 'le' instead of the feminine 'la'."
    },
    {
      "original": "le table",
      "correction": "la table",
      "error_type": "gender_agreement",
      "explanation": "'Table' is a feminine noun in French, so it needs the feminine article 'la' instead of the masculine 'le'."
    }
  ],
  "difficulty": "A1"
}

Example 3 -- Japanese particle error (non-Latin script):
Input: Target=Japanese, Native=English, Sentence="私は東京を住んでいます。"
Output:
{
  "corrected_sentence": "私は東京に住んでいます。",
  "is_correct": false,
  "errors": [
    {
      "original": "を",
      "correction": "に",
      "error_type": "grammar",
      "explanation": "The verb 住む (to live) uses the particle に to mark the place where you live, not を. Think of に as pointing to the location of your residence."
    }
  ],
  "difficulty": "A2"
}

Example 4 -- Correct German sentence (no errors):
Input: Target=German, Native=English, Sentence="Ich habe gestern einen interessanten Film gesehen."
Output:
{
  "corrected_sentence": "Ich habe gestern einen interessanten Film gesehen.",
  "is_correct": true,
  "errors": [],
  "difficulty": "B1"
}

Example 5 -- Korean particle error (non-Latin script):
Input: Target=Korean, Native=English, Sentence="나는 어제 학교를 갔어요."
Output:
{
  "corrected_sentence": "나는 어제 학교에 갔어요.",
  "is_correct": false,
  "errors": [
    {
      "original": "학교를",
      "correction": "학교에",
      "error_type": "grammar",
      "explanation": "When talking about going to a place, Korean uses the particle 에 (to/at) instead of 를 (object marker). You use 에 with movement verbs like 가다 (to go)."
    }
  ],
  "difficulty": "A2"
}

Example 6 -- Mandarin Chinese missing word:
Input: Target=Mandarin Chinese, Native=English, Sentence="我昨天在图书馆看了三个小时书。"
Output:
{
  "corrected_sentence": "我昨天在图书馆看了三个小时的书。",
  "is_correct": false,
  "errors": [
    {
      "original": "三个小时书",
      "correction": "三个小时的书",
      "error_type": "missing_word",
      "explanation": "In Chinese, when a time duration modifies what you did, you typically need 的 between the duration and the object. Adding 的 here makes the sentence flow naturally."
    }
  ],
  "difficulty": "B1"
}

Example 7 -- Portuguese spelling + grammar:
Input: Target=Portuguese, Native=English, Sentence="Eu quero comprar um prezente para minha irma, mas nao sei o que ela gosta."
Output:
{
  "corrected_sentence": "Eu quero comprar um presente para minha irma, mas nao sei do que ela gosta.",
  "is_correct": false,
  "errors": [
    {
      "original": "prezente",
      "correction": "presente",
      "error_type": "spelling",
      "explanation": "'Present/gift' in Portuguese is spelled 'presente' with an 's', not a 'z'."
    },
    {
      "original": "o que ela gosta",
      "correction": "do que ela gosta",
      "error_type": "grammar",
      "explanation": "The verb 'gostar' (to like) requires the preposition 'de'. So 'what she likes' becomes 'do que ela gosta' (de + o que)."
    }
  ],
  "difficulty": "B1"
}

Example 8 -- Arabic with explanation in English:
Input: Target=Arabic, Native=English, Sentence="انا ذهبت الى المدرسة امس"
Output:
{
  "corrected_sentence": "أنا ذهبتُ إلى المدرسة أمس.",
  "is_correct": false,
  "errors": [
    {
      "original": "انا",
      "correction": "أنا",
      "error_type": "spelling",
      "explanation": "The word 'I' in Arabic should be written with a hamza on the alif: أنا, not انا."
    },
    {
      "original": "الى",
      "correction": "إلى",
      "error_type": "spelling",
      "explanation": "The preposition 'to' needs a hamza under the alif: إلى, not الى."
    }
  ],
  "difficulty": "A2"
}

Example 9 -- Native language is NOT English (explanation in Spanish):
Input: Target=English, Native=Spanish, Sentence="I go to school yesterday."
Output:
{
  "corrected_sentence": "I went to school yesterday.",
  "is_correct": false,
  "errors": [
    {
      "original": "go",
      "correction": "went",
      "error_type": "conjugation",
      "explanation": "La palabra 'yesterday' indica que la accion ocurrio en el pasado. Por eso necesitas usar el pasado simple 'went' en lugar del presente 'go'."
    }
  ],
  "difficulty": "A2"
}

Example 10 -- Russian (Cyrillic script, grammatical case error):
Input: Target=Russian, Native=English, Sentence="Я живу в Москве и работаю в большой компания."
Output:
{
  "corrected_sentence": "Я живу в Москве и работаю в большой компании.",
  "is_correct": false,
  "errors": [
    {
      "original": "компания",
      "correction": "компании",
      "error_type": "grammar",
      "explanation": "After the preposition 'в' (in), nouns need to be in the prepositional case. 'Компания' (company) becomes 'компании' in this case."
    }
  ],
  "difficulty": "B1"
}
"""

# JSON schema for Structured Outputs
# - Passed to OpenAI API to enforce output structure at token generation level
# - strict=True prevents model from producing tokens that violate the schema

RESPONSE_SCHEMA: dict[str, Any] = {
    "name": "feedback_response",
    "strict": True,
    "schema": {
        "type": "object",
        "required": [
            "corrected_sentence",
            "is_correct",
            "errors",
            "difficulty",
        ],
        "additionalProperties": False,
        "properties": {
            "corrected_sentence": {
                "type": "string",
                "description": "The corrected version of the input sentence.",
            },
            "is_correct": {
                "type": "boolean",
                "description": "True if the original sentence had no errors.",
            },
            "errors": {
                "type": "array",
                "description": "List of errors found. Empty array if correct.",
                "items": {
                    "type": "object",
                    "required": [
                        "original",
                        "correction",
                        "error_type",
                        "explanation",
                    ],
                    "additionalProperties": False,
                    "properties": {
                        "original": {
                            "type": "string",
                            "description": "The erroneous text from the original sentence.",
                        },
                        "correction": {
                            "type": "string",
                            "description": "The corrected text.",
                        },
                        "error_type": {
                            "type": "string",
                            "enum": [
                                "grammar",
                                "spelling",
                                "word_choice",
                                "punctuation",
                                "word_order",
                                "missing_word",
                                "extra_word",
                                "conjugation",
                                "gender_agreement",
                                "number_agreement",
                                "tone_register",
                                "other",
                            ],
                            "description": "Category of the error.",
                        },
                        "explanation": {
                            "type": "string",
                            "description": "Friendly explanation written in the NATIVE language, never in the target language.",
                        },
                    },
                },
            },
            "difficulty": {
                "type": "string",
                "enum": ["A1", "A2", "B1", "B2", "C1", "C2"],
                "description": "CEFR difficulty level of the sentence.",
            },
        },
    },
}

# Valid error types that schema allows
_VALID_ERROR_TYPES = {
    "grammar", "spelling", "word_choice", "punctuation", "word_order",
    "missing_word", "extra_word", "conjugation", "gender_agreement",
    "number_agreement", "tone_register", "other",
}

# Common near labels LLM can produce instead of exact allowed strings
# Mapping them to correct value so response still passes schema validation
_ERROR_TYPE_ALIASES = {
    "verb_conjugation": "conjugation",
    "verb conjugation": "conjugation",
    "tense": "conjugation",
    "gender": "gender_agreement",
    "number": "number_agreement",
    "agreement": "gender_agreement",
    "register": "tone_register",
    "formality": "tone_register",
    "vocabulary": "word_choice",
    "lexical": "word_choice",
    "typo": "spelling",
    "misspelling": "spelling",
    "syntax": "grammar",
    "particle": "grammar",
    "preposition": "grammar",
    "article": "grammar",
    "missing word": "missing_word",
    "extra word": "extra_word",
    "word order": "word_order",
    "word choice": "word_choice",
}

def _normalize_error_type(raw: str) -> str:
    """Converts an error type string to an allowed value
    - If LLM produces a near label we map it to the correct allowed string
    - If the value is completely unrecognized, default to 'other'
    """
    cleaned = raw.strip().lower()
    if cleaned in _VALID_ERROR_TYPES:
        return cleaned
    if cleaned in _ERROR_TYPE_ALIASES:
        return _ERROR_TYPE_ALIASES[cleaned]
    return "other"

def _post_process(data: dict, original_sentence: str) -> dict:
    """Fix logical inconsistencies in LLM response
    - Even with a good prompt, LLMs can sometimes produce responses where
    is_correct doesn't match the errors list, or error_type values
    are slightly wrong. 
    - This function enforces consistency as a safety net
    """
    errors = data.get("errors", [])
    is_correct = data.get("is_correct", True)

    # Normalize every error_type to an allowed value
    for error in errors:
        if "error_type" in error:
            error["error_type"] = _normalize_error_type(error["error_type"])

    # If there are errors, is_correct must be False
    if len(errors) > 0 and is_correct:
        data["is_correct"] = False

    # If there are no errors, is_correct must be True and
    # corrected_sentence should match original
    if len(errors) == 0 and not is_correct:
        data["is_correct"] = True

    if len(errors) == 0:
        data["corrected_sentence"] = original_sentence

    # If corrected_sentence is empty, use original
    if not data.get("corrected_sentence", "").strip():
        data["corrected_sentence"] = original_sentence

    # Ensures difficulty has a valid default
    valid_difficulties = {"A1", "A2", "B1", "B2", "C1", "C2"}
    if data.get("difficulty") not in valid_difficulties:
        data["difficulty"] = "A2"
    return data

async def _call_llm(client: AsyncOpenAI, user_message: str) -> dict:
    """Call LLM and return parsed JSON
    - Uses OpenAI's Responses API with good cache utilization
    - Fall back to Chat Completions API if Responses API is not working for some reason
    """
    # Responses API with strict structured outputs
    # - Uses 'instructions' for system prompt and 'text.format' for schema enforcement
    try:
        response = await client.responses.create(
            model=openai_model,
            instructions=SYSTEM_PROMPT,
            input=user_message,
            text={
                "format": {
                    "type": "json_schema",
                    "name": "feedback_response",
                    "strict": True,
                    "schema": RESPONSE_SCHEMA["schema"],
                }
            },
            temperature=openai_temperature,
            store=False,
        )

        content = response.output_text
        if content is None:
            raise ValueError("Responses API returned no output text")

        # Logging token usage for cost monitoring
        if response.usage:
            logger.info(
                "Tokens (Responses API) -- input: %d, output: %d",
                response.usage.input_tokens,
                response.usage.output_tokens,
            )

        return json.loads(content)

    except (BadRequestError, APIStatusError) as exc:
        # The Responses API returned an error, so fall back to Chat Completions API
        logger.info(
            "Responses API error, falling back to Chat Completions: %s", exc
        )
    except (AttributeError, TypeError) as exc:
        # The SDK or provider doesn't have responses attribute at
        # all, then fall back to Chat Completions API
        logger.info(
            "Responses API not available, using Chat Completions: %s", exc
        )

    # Fallback: Chat Completions API
    # Tries strict json_schema first, then plain json_object
    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": user_message},
    ]

    try:
        response_cc = await client.chat.completions.create(
            model=openai_model,
            messages=messages,
            response_format={
                "type": "json_schema",
                "json_schema": RESPONSE_SCHEMA,
            },
            temperature=openai_temperature,
        )
    except BadRequestError as exc:
        # Provider does not support json_schema
        # So fall back to plain json_object mode
        logger.warning(
            "json_schema not supported, using json_object mode: %s", exc
        )
        response_cc = await client.chat.completions.create(
            model=openai_model,
            messages=messages,
            response_format={"type": "json_object"},
            temperature=openai_temperature,
        )

    if not response_cc.choices:
        raise ValueError("Chat Completions returned empty choices list")

    content = response_cc.choices[0].message.content
    if content is None:
        raise ValueError("Chat Completions returned None content")

    # Log token usage.
    if response_cc.usage:
        cached_tokens = "N/A"
        details = getattr(response_cc.usage, "prompt_tokens_details", None)
        if details is not None:
            cached_tokens = getattr(details, "cached_tokens", "N/A")
        logger.info(
            "Tokens (Chat Completions) -- prompt: %d, completion: %d, cached: %s",
            response_cc.usage.prompt_tokens,
            response_cc.usage.completion_tokens,
            cached_tokens,
        )

    return json.loads(content)

_RETRYABLE_ERRORS = (APITimeoutError, APIConnectionError)
_MAX_RETRIES = 2

# Base delay in seconds b/w retries, doubles each attempt
_RETRY_BASE_DELAY = 1.0

def _is_retryable_rate_limit(exc: RateLimitError) -> bool:
    """Checks if a rate limit error is worth retrying.
    - Returns True for normal rate limits that clear after a short wait
    - Returns False for insufficient_quota errors since that means the
    account has no money and retrying won't work
    """
    error_body = getattr(exc, "body", None)
    if isinstance(error_body, dict):
        code = error_body.get("error", {}).get("code", "")
        if code == "insufficient_quota":
            return False
    return True

async def get_feedback(request: FeedbackRequest) -> FeedbackResponse:
    """Analyze a learner's sentence and return structured feedback

    Flow:
    1. Check in-memory cache for a previous identical request
    2. If not cached, call LLM with automatic fallback from
    strict json_schema mode to plain json_object mode
    3. Retry on failures worth retrying with exponential backoff
    4. Post-process response to enforce logical consistency
    5. Validate with Pydantic and cache result
    """
    # Check cache
    cache_key = make_cache_key(
        request.sentence, request.target_language, request.native_language
    )
    cached = get_cached(cache_key)
    if cached is not None:
        logger.info("Cache hit for key: %s", cache_key[:80])
        return FeedbackResponse(**cached)

    # Build user message
    client = _get_client()

    user_message = (
        f"Target language: {request.target_language}\n"
        f"Native language: {request.native_language}\n"
        f"Sentence: {request.sentence}\n"
        f"Write all explanations in {request.native_language}."
    )

    # Call with retry logic for errors worth retrying
    last_error: Exception | None = None
    for attempt in range(_MAX_RETRIES + 1):
        try:
            data = await _call_llm(client, user_message)
            break  # Success.
        except RateLimitError as exc:
            # Only retry if temporary rate limit, not insufficient_quota error
            if not _is_retryable_rate_limit(exc):
                logger.error("Non-retryable rate limit error: %s", exc)
                raise
            last_error = exc
        except _RETRYABLE_ERRORS as exc:
            last_error = exc
        except (json.JSONDecodeError, ValueError) as exc:
            # Bad JSON or empty response is worth retrying once since
            # LLM can produce valid output on the next attempt
            last_error = exc

        # Attempt failed, retry if budget allows for it
        if attempt < _MAX_RETRIES:
            delay = _RETRY_BASE_DELAY * (2 ** attempt)
            logger.warning(
                "Attempt %d/%d failed, retrying in %.1fs: %s",
                attempt + 1,
                _MAX_RETRIES + 1,
                delay,
                last_error,
            )
            await asyncio.sleep(delay)
        else:
            logger.error(
                "All %d attempts failed: %s", _MAX_RETRIES + 1, last_error
            )
            raise last_error  # type: ignore[misc]

    # Post-process for logical consistency
    data = _post_process(data, request.sentence)

    # Validate with Pydantic and cache
    result = FeedbackResponse(**data)
    set_cached(cache_key, data)

    return result